### ISSUE TITLE
Refactor User Image Upload

### ISSUE THREAD

**Issue by jhibbeard89** [LofftApp/lofft-mobile-app#103]
# Quick Fix
_Quick fixes are small issues that can be completed during other development phases, to complete one just add it as closed to the unrelated PR and add your name as dev_

## Details
The user image appears in multiple locations in varying styles, this needs to be refactored and made into it's own components.

## To-do
- [ ] Create a user image components
- [ ] allow it to take parameters to react to the state of the app. 
- [ ] Follow a common style and design if no image is present. 

## Notes
This has already been refactored once, but issues occurred with the original refactor, a new version was developed and this has not been created into its own component.
