### ISSUE TITLE
Request Payment

### ISSUE THREAD

**Issue by jhibbeard89** [LofftApp/lofft-mobile-app#19]
# Feature Request

_Use this form to outline potential new features or planned features in Lofft_

---

### Feature experience

- As a `User` I can add a new payment
- As a `User` I can request individual payments.
- As a `User` I can split the requests evenly or request individual amounts from each user.
- As a `User` I can set if the payments/pot is recurring or closes once the debt is paid.

### To-do

- [ ]  Create a request form for payments
- [ ]  Allow for the total amount to be added (Specify € initially)
- [ ]  Get all members of the WG in a list to choose from to add to the payment.

### Design
<img width="637" alt="Screenshot 2021-12-23 at 15 05 18" src="https://user-images.githubusercontent.com/5392107/147258288-a21edad2-2e7d-47ef-a7a7-910bd182bb0d.png">

**Comment by jhibbeard89** [comment]
## Update 29.08
This is part of the lofft management section, and has been parked until further notice.
