### ISSUE TITLE
Make a Payment

### ISSUE THREAD

**Issue by jhibbeard89** [LofftApp/lofft-mobile-app#20]
# Feature Request

_Use this form to outline potential new features or planned features in Lofft_

---

## Feature description
This page should allow the `User` to pay their pot, show details of the payment and how it is split. The user should be able to select single, later and recurring payments. 

### Feature experience

- As a `User` I can choose whom to pay, the `pot` or `user`
- As a `User` I can choose to pay now, on a date or recurring.
- As a `User` I can select method of payment.
- As a `User` I can break down how much will be paid.

### To-do

- [ ]  List payment information from database.
- [ ]  Add the ability to select who I am paying.
- [ ]  Allow for a breakdown of payments.
- [ ]  Show warning if the number entered in recipients is greater than owed value.

### Design
<img width="566" alt="Screenshot 2021-12-10 at 07 48 11" src="https://user-images.githubusercontent.com/5392107/145529930-aa7ae423-ab0a-49a3-9564-6303295a6fb7.png">

**Comment by jhibbeard89** [comment]
## Update 29.08
This is part of the lofft management section, and has been parked until further notice.
