### ISSUE TITLE
Make a payment overview screens

### ISSUE THREAD

**Issue by jhibbeard89** [LofftApp/lofft-mobile-app#21]
# Feature Request

_Use this form to outline potential new features or planned features in Lofft_

**[Notion Link](https://www.notion.so/lofftapp/Make-a-payment-overview-screens-18ad5d27bd55467496333bd1870a0166)**

---

## Feature description
Allows the user to view an overview of their payments to users, this shows a divide between which user the payment is due. 

### Feature experience

- As a `User` I can view a direct breakdown of payments owed
- As a `User` I can break down a split of payments
- As a `User` I can add payment methods (Coming soon feature)

### To-do

- [ ]  Add a selection of payment options, if no payment options exist add new payment method.
- [ ]  In this stage this should be faded out Black or Lavender[30] with a note saying coming soon.
- [x]  Show a list of recipients and their details.
- [x]  Show how much is owed to each participant.

### Design
<img width="269" alt="Screenshot 2021-12-10 at 07 34 34" src="https://user-images.githubusercontent.com/5392107/145528474-22b300cf-eba0-43f1-b68d-4feff8c2ecf1.png">
<img width="271" alt="Screenshot 2021-12-10 at 07 34 47" src="https://user-images.githubusercontent.com/5392107/145528501-4bcc7bed-92b5-41a4-acf1-0c32eb02e011.png">

**Comment by jhibbeard89** [comment]
## Update 29.08
This is part of the lofft management section, and has been parked until further notice.
