### ISSUE TITLE
Pending Payments

### ISSUE THREAD

**Issue by jhibbeard89** [LofftApp/lofft-mobile-app#22]
# Feature Request

_Use this form to outline potential new features or planned features in Lofft_

**[Notion Link](https://www.notion.so/lofftapp/Pending-Payments-2b311c778130433eb807a0fda8dcb7aa)**

---

## Feature description
A user can view what payments they have upcoming and choose to pay the total amount or any upcoming bills. 

### Feature experience

- As a `User` I can view upcoming payments.
- As a `User` I can choose to pay by item.

### To-do

- [ ]  Add header showing total payment.
- [ ]  Check for each item owed.
- [ ]  Allow the `User` to choose to pay for each item.

### Design
<img width="269" alt="Screenshot 2021-12-10 at 07 14 32" src="https://user-images.githubusercontent.com/5392107/145526384-99d5332d-7158-4052-875f-df7b96f1d67b.png">

**Comment by jhibbeard89** [comment]
## Update 29.08
This is part of the lofft management section, and has been parked until further notice.
