### ISSUE TITLE
WAY Questions

### ISSUE THREAD

**Issue by jhibbeard89** [LofftApp/lofft-mobile-app#24]
# Feature Request

_Use this form to outline potential new feaures or planned features in lofft_

**[Notion Link](https://www.notion.so/lofftapp/WAY-Questions-Screen-1b3e78c70bed4b53b7c295809af38dde)**

---

### Feature experience

- As a `User` I can answer a series of questions to generate a personality profile. 

### Todo

**Pre Development**

- [ ]  Design the Way Question flow.
- [ ]  Write potential questions.
- [ ]  Understand and build a scoring matrix.

**Design Phase**

- [ ]  Design the interactions and experience for the user.
- [ ]  How will the score be shown if so

**Development Phase**

- [ ]

### Potential Challenges

-

---

## Suggested Feature

_**Please fill in bellow if you are suggesting a feature**_

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jhibbeard89** [comment]
# Team Involvement

This will require a discussion with each member of the team and Freddie to ensure we have strong questions and to organise how to use the data to rank potential flat shares.

**Comment by jhibbeard89** [comment]
## Update 29.08

This has now been added to the development pipline and will be completed during `sprint 2`
