### ISSUE TITLE
Import Google Firebase

### ISSUE THREAD

**Issue by jhibbeard89** [LofftApp/lofft-mobile-app#27]
# Feature Request

---

## Feature description
In the current examples, the database is operated through heroku using Postgresql. Though due to its security and ability to take pressure of us during this development stage I will test firebase. 

### Todo

- [ ] Add the Google Firebase API
- [ ] Build a user interaction from email, google and apple signin parameters 
- [ ] Store this data in the db

### Design

_no design components_
