### ISSUE TITLE
Options page needs updating to the new design. 

### ISSUE THREAD

**Issue by jhibbeard89** [LofftApp/lofft-mobile-app#72]
# Quick Fix
_Quick fixes are small issues that can be completed during other development phases, to complete one just add it as closed to the unrelated PR and add your name as dev_

The `Options`page has some minor redesign to it, the options are spread further apart and the button is inverted and red instead of grey. 

## Details
_A description of what needs changing, add which page or how to get there or if it's a component_
<img width="257" alt="Screenshot 2022-04-05 at 11 03 15" src="https://user-images.githubusercontent.com/5392107/161730381-fc4b62ea-d866-4723-a179-495e191b531d.png">

## To-do
- [ ] add margin to the options
- [ ] Invert the `sign out` button
- [ ] Make the button color red. 

## Notes

All components are already created, the style sheet just needs adapting.

**Comment by jhibbeard89** [comment]
Will take this on and edit the options page.
