### ISSUE TITLE
Update edit, save and cancel buttons for Profile and Lofft edits

### ISSUE THREAD

**Issue by jhibbeard89** [LofftApp/lofft-mobile-app#73]
# Quick Fix
_Quick fixes are small issues that can be completed during other development phases, to complete one just add it as closed to the unrelated PR and add your name as dev_
This is a design update with Figma, the icons are changing and becoming colored buttons to allow the user to update and save edits on their profile or lofft page. 

## Details
_A description of what needs changing, add which page or how to get there or if it's a component_
<img width="551" alt="Screenshot 2022-04-05 at 11 07 13" src="https://user-images.githubusercontent.com/5392107/161731007-1184bd6a-03c2-4087-ab69-f50a6904bb01.png">

## To-do
- [x] The edit button should become blue with a pencil bg
- [x] The save button should be a tick and green bg
- [x] The cancel button should be an x with red bg.

**Comment by jhibbeard89** [comment]
# Completed
This was completed in a previous PR
