### ISSUE TITLE
Attend and reject button, events

### ISSUE THREAD

**Issue by jhibbeard89** [LofftApp/lofft-mobile-app#86]
# Feature Request
A user should be able to attend, reject and created user delete an event. 
### Feature experience

- As a `User` I can attend or reject an event
- As a `Event creator` I can create an event

### To-do

- [ ] Attend button action.
- [ ] Reject Button action.
- [ ] Delete button action.

### Design
![Screenshot 2022-05-05 at 10 17 43](https://user-images.githubusercontent.com/5392107/166885995-5c64cea3-2038-4435-97bc-1b352af34f50.png)
